version: 2
jobs:
  test-bot-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-r
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          brew cask install xquartz
      - run: |
          brew --version
          brew update
          cd $(brew --repo)
          if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
          git fetch origin --tags
          git reset --hard origin/master
          brew --env
          brew config
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
          git fetch origin
          git reset --hard origin/master
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          echo $repo
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 60m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup --local

  test-bot-linux:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-r
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common debconf-utils
          sudo apt-get install -y zip unzip
      - run: |
          brew --version
          brew update
          cd $(brew --repo)
          if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
          git fetch origin --tags
          git reset --hard origin/master
          brew --env
          brew config
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          if [ -e .git/shallow ]; then echo git fetch --unshallow; fi
          git fetch origin
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          echo $repo
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 60m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew install patchelf
            brew test-bot --skip-setup --local

  bottle-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-r
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          brew cask install xquartz
      - checkout
      - run:
          no_output_timeout: 60m
          command: |
            brew update
            TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
            mkdir -p $TAP_PATH
            cp -a ./ $TAP_PATH/
            brew tap --repair
            RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
            FORMULA=$(echo "$RELEASE_TAG" | sed -nE 's/(^[@a-z0-9\.\-]*)-[0-9\._]*$/\1/p')
            brew install --build-from-source --build-bottle $FORMULA
            mkdir -p /tmp/bottles
            cd /tmp/bottles
            BOTTLE_ROOT_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/$RELEASE_TAG
            brew bottle --json --root-url=$BOTTLE_ROOT_URL $FORMULA
      - run: |
            # modify merge message platform tag
            cd /tmp/bottles
            sed -i '' 's/"sierra"/"sierra_or_later"/g' *.sierra.*.json
      - run: |
            # upload bottles to github releases
            brew tap tcnksm/ghr
            brew install ghr
            RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
            ghr --username $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --token $GITHUB_TOKEN --replace "$RELEASE_TAG" /tmp/bottles
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles

  bottle-linux:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-r
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common debconf-utils
          sudo apt-get install -y zip unzip
      - checkout
      - run:
          no_output_timeout: 60m
          command: |
            brew update
            TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
            mkdir -p $TAP_PATH
            cp -a ./ $TAP_PATH/
            brew tap --repair
            RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
            FORMULA=$(echo "$RELEASE_TAG" | sed -nE 's/(^[@a-z0-9\.\-]*)-[0-9\._]*$/\1/p')
            brew install --build-from-source --build-bottle $FORMULA
            mkdir -p /tmp/bottles
            cd /tmp/bottles
            BOTTLE_ROOT_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/$RELEASE_TAG
            brew bottle --json --root-url=$BOTTLE_ROOT_URL $FORMULA
      - run: |
            # upload bottles to github releases
            brew install unzip
            curl -L https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip -o /tmp/ghr.zip
            mkdir -p ~/.local/bin/
            unzip /tmp/ghr.zip  -d ~/.local/bin/
            RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
            ~/.local/bin/ghr --username $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --token $GITHUB_TOKEN --replace "$RELEASE_TAG" /tmp/bottles
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles

  create-macos-pr:
    macos:
      xcode: "9.0"
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: |
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - run: |
          brew install hub
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
          brew tap --repair
          # create pull request
          cd $TAP_PATH
          git reset --hard origin/$CIRCLE_BRANCH
          brew bottle --merge --write /tmp/workspace/bottles/*.json
          RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
          git checkout -b "$RELEASE_TAG#pr"
          git remote set-url origin https://$CIRCLE_PROJECT_USERNAME:$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          git push --set-upstream --force origin "$RELEASE_TAG#pr"
          hub pull-request -m "$(git log -1 --pretty=%B)"

  create-pr:
    docker:
      - image: linuxbrew/linuxbrew
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: |
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - run: |
          brew install hub
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
          brew tap --repair
          # create pull request
          cd $TAP_PATH
          git reset --hard origin/$CIRCLE_BRANCH
          brew bottle --merge --write /tmp/workspace/bottles/*.json
          RELEASE_TAG=$(echo "$CIRCLE_BRANCH" | sed -nE 's/(^[@a-z0-9\.\-]+-[0-9\._]+)#(macos-)?bottle$/\1/p')
          git checkout -b "$RELEASE_TAG#pr"
          git remote set-url origin https://$CIRCLE_PROJECT_USERNAME:$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          git push --set-upstream --force origin "$RELEASE_TAG#pr"
          hub pull-request -m "$(git log -1 --pretty=%B)"

workflows:
  version: 2
  build:
    jobs:
      - test-bot-macos:
          filters:
            branches:
              ignore: /master|.*#pr|.*#bottle|.*#macos-bottle/
      - test-bot-linux:
          filters:
            branches:
              ignore: /master|.*#pr|.*#bottle|.*#macos-bottle/
      - create-macos-pr:
          requires:
            - bottle-macos
          filters:
            branches:
              only: /.*#macos-bottle/
      - create-pr:
          requires:
            - bottle-macos
            - bottle-linux
          filters:
            branches:
              only: /.*#bottle/
      - bottle-macos:
          filters:
            branches:
              only: /.*#bottle|.*#macos-bottle/
      - bottle-linux:
          filters:
            branches:
              only: /.*#bottle/
