version: 2
jobs:
  test-bot-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-rstudio-server
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          cd $(brew --repo)
          git fetch origin --tags
          git reset --hard origin/master
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git reset --hard origin/master
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
      - run:
          no_output_timeout: 60m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup

  test-bot-linux:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-rstudio-server
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          cd $(brew --repo)
          git fetch origin --tags
          git reset --hard origin/master
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - run: |
          brew install jdk@8  # ant requires it
          brew link jdk@8 --force
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git reset --hard origin/master
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
      - run:
          no_output_timeout: 60m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup

  bottle-macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          no_output_timeout: 60m
          command: |
            TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
            mkdir -p $TAP_PATH
            cp -a ./ $TAP_PATH/
            brew tap --repair
            FORMULA=$(echo "$CIRCLE_TAG" | sed -nE 's/(^[a-z\-]*)-[0-9\._]*$/\1/p')
            brew install --build-from-source --build-bottle $FORMULA
            mkdir -p /tmp/bottles
            cd /tmp/bottles
            BOTTLE_ROOT_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/$CIRCLE_TAG
            brew bottle --json --root-url=$BOTTLE_ROOT_URL $FORMULA
      - run: |
            # modify merge message platform tag
            cd /tmp/bottles
            sed -i '' 's/"sierra"/"sierra_or_later"/g' *.sierra.*.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles

  bottle-linux:
    docker:
      - image: linuxbrew/linuxbrew
    steps:
      - checkout
      - run: |
            brew install jdk@8  # ant requires it
            brew link jdk@8 --force
      - run:
          no_output_timeout: 60m
          command: |
            TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
            mkdir -p $TAP_PATH
            cp -a ./ $TAP_PATH/
            brew tap --repair
            FORMULA=$(echo "$CIRCLE_TAG" | sed -nE 's/(^[a-z\-]*)-[0-9\._]*$/\1/p')
            brew install --build-from-source --build-bottle $FORMULA
            mkdir -p /tmp/bottles
            cd /tmp/bottles
            BOTTLE_ROOT_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/$CIRCLE_TAG
            brew bottle --json --root-url=$BOTTLE_ROOT_URL $FORMULA

      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles

  upload-bottles:
    docker:
      - image: linuxbrew/linuxbrew
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: |
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - run: |
          # upload bottles to github releases
          brew install unzip
          curl -L https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip -o /tmp/ghr.zip
          mkdir -p ~/.local/bin/
          unzip /tmp/ghr.zip  -d ~/.local/bin/
          ~/.local/bin/ghr --username $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --token $GITHUB_TOKEN --replace "$CIRCLE_TAG" /tmp/workspace/bottles
      - run: |
          brew install hub
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
          brew tap --repair
          # create pull request
          cd $TAP_PATH
          git reset --hard origin/master
          brew bottle --merge --write /tmp/workspace/bottles/*.json
          git checkout -b "$CIRCLE_TAG#pr"
          git remote set-url origin https://$CIRCLE_PROJECT_USERNAME:$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          git push --set-upstream --force origin "$CIRCLE_TAG#pr"
          hub pull-request -m "$(git log -1 --pretty=%B)"

workflows:
  version: 2
  build:
    jobs:
      - test-bot-macos:
          filters:
            branches:
              ignore: /master|.*#pr/
      - test-bot-linux:
          filters:
            branches:
              ignore: /master|.*#pr/
      - upload-bottles:
          requires:
            - bottle-macos
            - bottle-linux
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - bottle-macos:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - bottle-linux:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
