version: 2
jobs:
  test-bot:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/randy3k/homebrew-rstudio-server
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          brew update
          cd $(brew --repo)
          git fetch origin --tags
          git reset --hard origin/master
          git config --global user.name randy3k
          git config --global user.email randy.cs.lai@gmail.com
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git reset --hard origin/master
          TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $TAP_PATH
          cp -a ./ $TAP_PATH/
      - run:
          no_output_timeout: 60m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup

  deploy-tag:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          no_output_timeout: 60m
          command: |
            TAP_PATH=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
            mkdir -p $TAP_PATH
            cp -a ./ $TAP_PATH/
            brew tap --repair
            FORMULA=$(echo "$CIRCLE_TAG" | sed -nE 's/(^[a-z\-]*)-[0-9\.]*$/\1/p')
            echo "brew install $FORMULA"
            brew install --build-from-source --build-bottle $FORMULA
            mkdir -p /tmp/bottles
            cd /tmp/bottles
            BOTTLE_ROOT_URL=https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/download/$CIRCLE_TAG
            brew bottle --no-rebuild --json --root-url=$BOTTLE_ROOT_URL $FORMULA
            brew install tcnksm/ghr/ghr
            mkdir -p /tmp/dist
            for f in /tmp/bottles/$FORMULA*; do cp "$f" /tmp/dist/; done
            ghr --username randy3k --token $GITHUB_TOKEN --replace "$CIRCLE_TAG" /tmp/dist

workflows:
  version: 2
  build:
    jobs:
      - test-bot:
          filters:
            branches:
              ignore: master

      - deploy-tag:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
